/**
 * Hand-written mirror of the Supabase schema in `docs/sql/`.
 *
 * This is not generated by the Supabase CLI (no CLI access in this
 * environment) — it's kept in sync manually with the SQL migrations.
 * Column names are `snake_case` to match Postgres exactly; the
 * `camelCase` versions in `src/features/.../types.ts` are the
 * application-facing shapes mapped from these rows at the data-access
 * layer (see `src/lib/supabase/mappers.ts`).
 */

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string;
          display_name: string;
          avatar_url: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          username: string;
          display_name: string;
          avatar_url?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          username?: string;
          display_name?: string;
          avatar_url?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      rooms: {
        Row: {
          id: string;
          name: string;
          code: string;
          host_id: string;
          status: "waiting" | "ready_to_start" | "playing" | "finished";
          game_id: string | null;
          max_players: number;
          min_ready_players: number;
          is_private: boolean;
          invite_expiry_minutes: number;
          created_at: string;
          expires_at: string | null;
          finished_at: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          code: string;
          host_id: string;
          status?: "waiting" | "ready_to_start" | "playing" | "finished";
          game_id?: string | null;
          max_players?: number;
          min_ready_players?: number;
          is_private?: boolean;
          invite_expiry_minutes?: number;
          created_at?: string;
          expires_at?: string | null;
          finished_at?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          code?: string;
          host_id?: string;
          status?: "waiting" | "ready_to_start" | "playing" | "finished";
          game_id?: string | null;
          max_players?: number;
          min_ready_players?: number;
          is_private?: boolean;
          invite_expiry_minutes?: number;
          created_at?: string;
          expires_at?: string | null;
          finished_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "rooms_host_id_fkey";
            columns: ["host_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      room_players: {
        Row: {
          id: string;
          room_id: string;
          user_id: string;
          display_name: string;
          seat: number;
          is_host: boolean;
          is_ready: boolean;
          joined_at: string;
        };
        Insert: {
          id?: string;
          room_id: string;
          user_id: string;
          display_name: string;
          seat: number;
          is_host?: boolean;
          is_ready?: boolean;
          joined_at?: string;
        };
        Update: {
          id?: string;
          room_id?: string;
          user_id?: string;
          display_name?: string;
          seat?: number;
          is_host?: boolean;
          is_ready?: boolean;
          joined_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "room_players_room_id_fkey";
            columns: ["room_id"];
            isOneToOne: false;
            referencedRelation: "rooms";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "room_players_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
  };
}

export type ProfileRow = Database["public"]["Tables"]["profiles"]["Row"];
export type RoomRow = Database["public"]["Tables"]["rooms"]["Row"];
export type RoomPlayerRow = Database["public"]["Tables"]["room_players"]["Row"];
